apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lira
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-lira@sha256:daf78eb30b2d718059a71334c0ddd4d149a337954cc3cca5ef144448cc729780
        name: my-nodejs
        resources: {}
status: {}
